
import React from 'react';
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/molecules/navbar/navbar';
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

export function generateStaticParams() {

  return [{locale: 'fr'}, {locale: 'en'}];

}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutParams {
  locale: string;
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode,
  params: LayoutParams,
}) {

  let messages;
  try {
    messages = (await import(`../../messages/${params.locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
      <NextIntlClientProvider locale={params.locale} messages={messages}>
        {/* Ajouter ici le contenu global de la mise en page */}
        <Navbar />
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}

